apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: golang-redis-app
  labels:
    app: {{ .Values.service.name }}
spec:
  endpoints:
  - interval: 10s
    port: http
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
