Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  # имя пользователя
  config.ssh.username = 'vagrant'
  # пароль пользователя
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.name = "usk8s1vg"
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.hostname = "us22minikube1vg"

  config.vm.synced_folder ".", "C:\inshare",
    owner: "www-data", group: "www-data"
  
  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.network "forwarded_port", guest: 3306, host: 33060

  config.vm.network "private_network", ip: "192.168.10.10"

  config.vm.provision "shell", path: "provision.sh"
  
end