version: "3.8"  # Используйте версию 3.8 для поддержки всех функций Swarm
services:
  web:
    image: nginx:latest  # Используем образ nginx
    ports:
      - "8081:80"  # Пробрасываем порт 8080 на хосте на порт 80 в контейнере
    deploy:
      mode: replicated  # Режим репликации
      replicas: 3  # Количество реплик
      restart_policy:
        condition: on-failure  # Перезапускать только при ошибках
        delay: 5s  # Задержка перед перезапуском
        max_attempts: 3  # Максимальное количество попыток перезапуска
        window: 120s  # Время для оценки успешности перезапуска
      update_config:
        parallelism: 1  # Количество контейнеров, обновляемых одновременно
        delay: 10s  # Задержка между обновлениями
      rollback_config:
        parallelism: 1  # Количество контейнеров, откатываемых одновременно
        delay: 10s  # Задержка между откатами
      resources:
        limits:
          cpus: "0.5"  # Ограничение на использование CPU
          memory: "512M"  # Ограничение на использование памяти
        reservations:
          cpus: "0.1"  # Резервирование CPU
          memory: "256M"  # Резервирование памяти
    networks:
      - webnet  # Подключаем сервис к сети

networks:
  webnet:  # Определяем сеть
    driver: overlay  # Используем драйвер overlay для Swarm