apiVersion: v1
kind: Pod
metadata:
    name: env-pod
spec:
    restartPolicy: Never
    containers:
    - name: env-container
      image: ubuntu:latest
      command: ["env"]
      env:
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sample-secret
              key: password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: sample-config
              key: DB_HOST