apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: sample-claim
    namespace: default
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: csi-cinder-classic