apiVersion: v1
kind: Secret
metadata:
    name: sample-secret
type: Opaque
data:
    # Здесь заданы значения в base64, чтобы скрыть от случайных взглядов
    password: cGFzc3dvcmQ=
    api_key: YXBpX2tleQ==