
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubectl-tester
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubectl-tester
  template:
    metadata:
      labels:
        app: kubectl-tester
    spec:
      serviceAccountName: devops-reader  # Ключевой параметр!
      containers:
      - name: kubectl
        image: bitnami/kubectl
        command: ["sleep", "infinity"]  # Чтобы под не завершался сразу