apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-reader
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: devops-reader
  namespace: default
roleRef:
  kind: Role
  name: read-role
  apiGroup: rbac.authorization.k8s.io