apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-intensive-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-intensive
  template:
    metadata:
      labels:
        app: memory-intensive
    spec:
      containers:
      - name: java-app
        image: openjdk:11-jre-slim
        command: ["sleep", "infinity"]   # вместо ["java", "-Xmx512M", "-Xms256M", "-jar", "/app.jar"], так как в этом случа нужно указывать или собирать образ, для теста сделал sleep
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "512Mi"