apiVersion: batch/v1
kind: Job
metadata:
  name: memory-loader
spec:
  template:
    spec:
      containers:
      - name: loader
        image: progrium/stress
        command: ["stress", "--vm", "2", "--vm-bytes", "300M", "--vm-hang", "1"]
      restartPolicy: Never