services:
  wireguard:
    build: .  # Собираем образ из Dockerfile
    # image: ghcr.io/wg-easy/wg-easy:latest  # или Используем официальный образ wg-easy
    container_name: ${CONTAINER_NAME}
    environment:
      - WG_HOST=${WG_HOST}  # Ваш IP-адрес
      - PASSWORD_HASH=${PASSWORD_HASH}  # Пароль для доступа к веб-интерфейсу
    volumes:
      - ${CONFIG_DIR}:/etc/wireguard  # Храним конфигурацию WireGuard на хосте
    ports:
      - "51820:51820/udp"  # Порт для WireGuard (UDP)
      - "51821:51821/tcp"  # Порт для веб-интерфейса (TCP)
    cap_add:
      - NET_ADMIN  # Привилегии для работы с сетью
      - SYS_MODULE  # Привилегии для работы с модулями ядра
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1  # Настройки ядра для WireGuard
      - net.ipv4.ip_forward=1
    restart: unless-stopped  # Автоматический перезапуск контейнера