version: "3.8"
services:
  wireguard:
    build: .  # Собираем образ из Dockerfile
    # image: ghcr.io/wg-easy/wg-easy:latest  # или Используем официальный образ wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=my_ip  # Ваш IP-адрес
      - PASSWORD=my_secure_password  # Пароль для доступа к веб-интерфейсу
    volumes:
      - ./config/wg-easy:/etc/wireguard  # Храним конфигурацию WireGuard на хосте
    ports:
      - "51820:51820/udp"  # Порт для WireGuard (UDP)
      - "51821:51821/tcp"  # Порт для веб-интерфейса (TCP)
    cap_add:
      - NET_ADMIN  # Привилегии для работы с сетью
      - SYS_MODULE  # Привилегии для работы с модулями ядра
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1  # Настройки ядра для WireGuard
      - net.ipv4.ip_forward=1
    restart: unless-stopped  # Автоматический перезапуск контейнера