apiVersion: apps/v1 
kind: Deployment
metadata:
  name: app-cpu
  namespace: default
  labels:
    app: app-cpu
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: app-cpu
  template:
    metadata:
      labels:
        app: app-cpu
    spec:
      containers:
      - image: trinitronx/python-simplehttpserver
        name: app-cpu
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app-cpu
  labels:
    app: app-cpu
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32080
  selector:
    app: app-cpu
  type: NodePort