version: v2
name: golang-redis-app-chart
description: A Helm chart for Kubernetes

type: application
version: 0.2.0 #добавляется в имя 
appVersion: 0.0.1

dependencies:
- name: redis
  version: 18.1.6
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: redis.enabled