apiVersion: v1
kind: Service
metadata:
  name: sample-site-clusterip #короткое имя, что бы ходить между сервисами
  labels:
    app: sample-site
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: sample-site
  type: ClusterIP