# Специальный под для доключения к созданным ресурсам. 
# заходим в него `kubectl exec deploy/toolkit -ti -- /bin/bash`
# можно проверить адрес сервиса внутри пода `nslookup sample-site-clusterip`
# nginx так же доступен и от сюда `curl http://sample-site-clusterip`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolkit
  namespace: default
  labels:
    app: toolkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolkit
  template:
    metadata:
      labels:
        app: toolkit
    spec:
      containers:
      - image: leodotcloud/swiss-army-knife
        name: toolkit