apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx20-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx20
  template:
    metadata:
      labels:
        app: nginx20
    spec:
      containers:
      - name: nginx20
        image: nginx:latest
        ports:
        - containerPort: 80
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx20
            topologyKey: "kubernetes.io/hostname"